### ISSUE TITLE
clarification on the use of expect_column_values_to_be_in_set

### ISSUE THREAD

**Issue by s-vinay** [calogica/dbt-expectations#107]
Data warehouse: Bigquery

The test "expect_column_values_to_be_in_set" is validating the list of values in a particular column with the input set provided. When we have an additional value in the parameter (which does not exist in the column), the test is still successful. This is similar to the issue #100.

To explain the scenario,
- let us say we have a payment_method column which has distinct values "credit_card", "bank_transfer", "coupon", "gift_card" and "cash"
- But value "cash" does not exist in the values of our transformed column due to a bug (let us say)
- tester is performing a validation with the value_set = ["credit_card", "bank_transfer", "coupon", "gift_card", "cash"]
- this test turns out to be successful (as all other input values exist in the column) even though the value "cash" does not exist in the column

Ideally, it is better that the test fails because one value in the parameter input does not exist in the column. Thoughts ?

**Comment by clausherther** [comment]
Hi @s-vinay ! I _think_ this is working as designed. Being "in a set" doesn't necessarily mean it's an exact match of the entire set, which is why I implemented this is a left join.  The issue in #100 was that that test was meant to explicitly check that the list of columns match the _entire_ set.
What we may need is to either add a parameter here to force stricter evaluation, or to add something like `expect_column_values_to_match_set`. Alternatively, you could use `https://docs.getdbt.com/reference/resource-properties/tests#accepted_values`.

**Comment by s-vinay** [comment]
Hello @clausherther , completely agree. Makes sense to have an additional test for exact match of a set.

**Comment by Sp31dy** [comment]
Hello @clausherther,  whats the difference between accepted values or expect_column_values_to_be_in_set"?
