### ISSUE TITLE
Update documentation to reflect correct argument names

### ISSUE THREAD

**Issue by belasobral93** [calogica/dbt-expectations#175]
Example:
Docs show

tests:
  -- dbt_expectations.expect_table_column_count_to_be_between:
      **minimum**: 1
      **maximum**: 4

Which results in a compiler error. Macro shows arguments are actually **min-value** and **max-value**

**Comment by clausherther** [comment]
Hi @belasobral93 ! Thanks for this issue. Where are you seeing these docs?
The current docs show the correct parameters: https://github.com/calogica/dbt-expectations#expect_table_column_count_to_be_between

**Comment by belasobral93** [comment]
Hi @clausherther this is in [dbt's package hub](https://hub.getdbt.com/calogica/dbt_expectations/latest/) - i will close this issue and open one with dbt

**Comment by clausherther** [comment]
Hi @belasobral93 it's also correct on package hub, since they just pull the README from this repo: 
<img width="975" alt="image" src="https://user-images.githubusercontent.com/7342749/166545479-f359a32b-a7c1-4beb-ad3e-44bd29eb682d.png">

You want to make sure you're looking at the latest package hub version:
https://hub.getdbt.com/calogica/dbt_expectations/latest/
(note the `latest` in the URL)
