### ISSUE TITLE
[BUG] expect_column_distinct_count_to_equal

### ISSUE THREAD

**Issue by bab354** [calogica/dbt-expectations#27]
Was trying to use this test: expect_column_distinct_count_to_equal

but when I put it in my YML file like so:
![image](https://user-images.githubusercontent.com/25424439/111077386-f690ae00-84c6-11eb-9051-177815562d04.png)

I get the following error:
![image](https://user-images.githubusercontent.com/25424439/111077401-001a1600-84c7-11eb-95f7-c11830cdcc03.png)

**Comment by bab354** [comment]
DBT version: 0.19.0
dbt expectations package: 0.2.2

**Comment by bab354** [comment]
just upgraded to version 0.2.7 and it resolved itself but probably worth highlighting somewhere that that test may not work for older versions

**Comment by clausherther** [comment]
Hi @bab354! This test was a new addition in `0.2.4` (see https://github.com/calogica/dbt-expectations/releases/tag/0.2.4) which is why it didn't work with the older version.
The best way to stay current is to use dbt Hub which always has the latest release (see https://github.com/calogica/dbt-expectations#install).

**Comment by bab354** [comment]
ahh got it, thanks @clausherther sorry for the false alarm!
