### ISSUE TITLE
expect_column_values_to_be_in_set doesn't seem to be working

### ISSUE THREAD

**Issue by ahmedrad** [calogica/dbt-expectations#90]
Hi, 

I'm looking at the source code for `expect_column_values_to_be_in_set` and it doesn't look like it's validating the fields at all.

```
validation_errors as (
    -- values from the model that are not in the set
    select
        v.value_field
    from
        all_values v
        left join
        set_values s on v.value_field = s.value_field
    where
        v.value_field is null
)
```

I think to validate for errors either `v.value` needs to be `s.value` or the `left join` needs to be a `right join` .. I can submit a pull request this week but thought I'd let you know first as it might affect a lot of tests.

**Comment by clausherther** [comment]
Hi @ahmedrad, thanks for submitting this, really good find! You're right, we should make this:
```sql
where
    s.value_field is null
```
I think because of the way this is written, the integration test here unfortunately always passes, so this must have snuck by (good example of why we may have to explicitly test failures in the future).

Happy to accept your PR if you have the time, or I can fix it this week.

**Comment by clausherther** [comment]
Actually, looks like this isn't covered by an integration test, yikes! No wonder.
So, we also have to add a test in https://github.com/calogica/dbt-expectations/blob/main/integration_tests/models/schema_tests/schema.yml

**Comment by ahmedrad** [comment]
Pull request submitted: https://github.com/calogica/dbt-expectations/pull/91
