### ISSUE TITLE
expect_table_columns_to_match_ordered_list is failing on Redshift

### ISSUE THREAD

**Issue by mirosval** [calogica/dbt-expectations#99]
After the upgrade to `0.4` the [expectation](https://github.com/calogica/dbt-expectations/blob/ad9767114ff4159fdaafe00064525ce2b50ef743/macros/schema_tests/table_shape/expect_table_columns_to_match_ordered_list.sql) is failing on Redshift with

```
Invalid operation: failed to find conversion function from "unknown" to text;
```

I think this is because redshift cant guess the type of the `ordered_column_names` and `ordered_relation_column_names`. Locally I managed to get it to run by adding `::text` after.

```sql
select
  count(*) as failures,
  count(*) != 0 as should_warn,
  count(*) != 0 as should_error
from (
       with test_data as (

         select
           'COL_A, COL_B'::text as ordered_column_names,
           'COL_A, COL_B'::text as ordered_relation_column_names

       )
       select *
       from test_data
       where ordered_column_names != ordered_relation_column_names

     ) dbt_internal_test
```

**Comment by clausherther** [comment]
Thanks for raising this issue @mirosval ! Interesting, I'll check into this as much as I can, as well as the other issues you've opened. We don't officially support Redshift because we don't have a way to test against a RS cluster. But maybe there are some generic things we can do help with types etc that would also work on Redshift. I'll take a look by end of the week.
